general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a batch script to start Zebar.
  # Whether to automatically focus windows underneath the cursor.
  startup_commands: ['shell-exec zebar']

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  focus_follows_cursor: false
  # Whether to switch back and forth between the previously focused

  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false
  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true
    # Trigger for cursor jump:

    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    # trigger: "monitor_focus"
    trigger: "window_focus"
gaps:
  # Gap between adjacent windows.
  inner_gap: "2px"
  # Gap between windows and the screen edge.

  outer_gap:
    top: "30px"
    right: "2px"
    bottom: "2px"
    left: "2px"
window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#bea3c7"
  # Visual effects to apply to non-focused windows.

  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"
window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"
  # Sets the default options for when a new window is created. This also

  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true
      # Whether to show floating windows as always on top.

      shown_on_top: false
    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false
      # Whether to show fullscreen windows as always on top.

      shown_on_top: false
workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"
window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }
      - window_title: {regex: "[Pp]icture.in.[Pp]icture"}
        # Ignores picture-in-picture windows for browsers.

        window_class: {regex: "Chrome_WidgetWin_1|MozillaDialogClass"}
      - window_process: {equals: "PowerToys.PowerAccent"}
        # Ignore rules for various 3rd-party apps.
      - window_process: {equals: "Lively"}
        window_class: {regex: "HwndWrapper*"}
binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      - commands: ["wm-disable-binding-mode --name resize"]
        # Press enter/escape to return to default keybindings.

        bindings: ["escape", "enter"]
  - name: "pause"
    # When enabled, all keybindings are disabled except for alt+shift+p which

    # returns to default keybindings.
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+p"]
keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["alt+h", "alt+left", "alt+z"]
  - commands: ["focus --direction right"]
    bindings: ["alt+l", "alt+right", "alt+v"]
  - commands: ["focus --direction up"]
    bindings: ["alt+k", "alt+up", "alt+c"]
  - commands: ["focus --direction down"]
    bindings: ["alt+j", "alt+down", "alt+x"]
  - commands: ["move --direction left"]

    # Move focused window in a given direction.

    bindings: ["alt+shift+h", "alt+shift+left", "alt+shift+z"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right", "alt+shift+v"]
  - commands: ["move --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up", "alt+shift+c"]
  - commands: ["move --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down", "alt+shift+x"]
    # Resize focused window by a percentage or pixel amount.

  - commands: ["resize --width -2%"]
    bindings: ["alt+u"]
  - commands: ["resize --width +2%"]
    bindings: ["alt+p"]
  - commands: ["resize --height +2%"]
    bindings: ["alt+o"]
  - commands: ["resize --height -2%"]
    bindings: ["alt+i"]
  
    # As an alternative to the resize keybindings above, resize mode enables

    # the name 'resize'.
    # resizing via arrow keys or HJKL. The binding mode is defined above with
  - commands: ["wm-enable-binding-mode --name resize"]  
    bindings: ["alt+r"]
  - commands: ["wm-enable-binding-mode --name pause"]
    # Disables all keybindings until alt+shift+p is pressed again.

    bindings: ["alt+shift+p"]

    # bindings: ["alt+c"]
  - commands: ["toggle-floating --centered"]
    # Change focus from tiling windows -> floating -> fullscreen.

    # Change the focused window to be floating.
    # - commands: ["wm-cycle-focus"]
    bindings: ["alt+shift+space"]
  - commands: ["toggle-tiling"]
    # Change the focused window to be tiling.

    bindings: ["alt+t"]
  - commands: ["toggle-fullscreen"]
    # Change the focused window to be fullscreen.

    bindings: ["alt+f"]
  - commands: ["toggle-minimized"]
    # Minimize focused window.

    bindings: ["alt+m"]
  - commands: ["close"]
    # Close focused window.

    bindings: ["alt+shift+q"]
    # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["alt+shift+e"]

  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+w"]
    # Re-evaluate configuration file.		
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+r"]
    # Redraw all windows.
    # Launch CMD terminal. Alternatively, use `shell-exec wt` or

    # Terminal and Git Bash respectively.
    # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  - commands: ["shell-exec bash"]
    bindings: ["alt+enter"]

  - commands: ["focus --next-workspace"]
    # Focus the next/previous workspace defined in `workspaces` config.

    bindings: ["alt+s"]
  - commands: ["focus --prev-workspace"]
    bindings: ["alt+a"]
  - commands: ["focus --recent-workspace"]
    # Focus the workspace that last had focus.

    bindings: ["alt+d"]
  - commands: ["focus --workspace 1"]
    # Change focus to a workspace defined in `workspaces` config.

    bindings: ["alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["alt+9"]

    # Move the focused window's parent workspace to a monitor in a given
    # direction.

  - commands: ["move --prev-workspace", "focus --prev-workspace"]
    bindings: ["alt+shift+a"]

  - commands: ["move --next-workspace", "focus --next-workspace"]
    bindings: ["alt+shift+s"]

    # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["alt+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["alt+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["alt+shift+9"]
